import { LitVocabTerm } from './generated-vocab-acl'

/**
 * Generated by ontology generator [${generatorClassname}]
 * from the source RDF file [${sourceRdfResource}]
 * at '${generatedTimestamp}'.
 */

const _NAMESPACE = 'http://xmlns.com/foaf/0.1/'
function _NS (localName: any) { return (_NAMESPACE + localName) }

export const FOAF = {
  NAMESPACE: _NAMESPACE,
  NS: _NS,

  // *****************
  // All the Classes.
  // *****************

  /**
   *
   */
  Agent: new LitVocabTerm(_NS('Agent'))
,

  //
  // Marker allowing us put commas at the end of all lines above (only the last line does not have a comma).
  //
  END_OF_VOCAB: 'End of vocab.'
}
