import { LitVocabTerm } from './generated-vocab-acl'

/**
 * Generated by ontology generator [${generatorClassname}]
 * from the source RDF file [${sourceRdfResource}]
 * at '${generatedTimestamp}'.
 */

const _NAMESPACE = 'http://www.w3.org/1999/02/'
function _NS (localName: any) { return (_NAMESPACE + localName) }

export const RDF = {
  NAMESPACE: _NAMESPACE,
  NS: _NS,

  // *****************
  // All the Classes.
  // *****************

  /**
   * The subject is an instance of a class.
   */
  type: new LitVocabTerm(_NS('22-rdf-syntax-ns#type'))
    .addLabel('', 'type')
    .addComment('', `The subject is an instance of a class.`)
,

  //
  // Marker allowing us put commas at the end of all lines above (only the last line does not have a comma).
  //
  END_OF_VOCAB: 'End of vocab.'
}
