import { LitVocabTerm } from './generated-vocab-acl'

/**
 * Generated by ontology generator [${generatorClassname}]
 * from the source RDF file [${sourceRdfResource}]
 * at '${generatedTimestamp}'.
 */

const _NAMESPACE = 'http://www.w3.org/2006/vcard/'
function _NS (localName: any) { return (_NAMESPACE + localName) }

export const VCARD = {
  NAMESPACE: _NAMESPACE,
  NS: _NS,

  // *****************
  // All the Classes.
  // *****************

  /**
   * To include a member in the group this object represents. (This property can only be used by Group individuals)
   */
  hasMember: new LitVocabTerm(_NS('ns#hasMember'))
    .addLabel('en', 'has member')
    .addComment('en', `To include a member in the group this object represents. (This property can only be used by Group individuals)`)
,

  //
  // Marker allowing us put commas at the end of all lines above (only the last line does not have a comma).
  //
  END_OF_VOCAB: 'End of vocab.'
}
