import { LitVocabTerm } from './generated-vocab-acl'

/**
 * Generated by ontology generator [${generatorClassname}]
 * from the source RDF file [${sourceRdfResource}]
 * at '${generatedTimestamp}'.
 */

const _NAMESPACE = 'http://www.w3.org/ns/ldp#'
function _NS (localName: any) { return (_NAMESPACE + localName) }

export const LDP = {
  NAMESPACE: _NAMESPACE,
  NS: _NS,

  // *****************
  // All the Classes.
  // *****************

  /**
   * An LDPC that uses a predefined predicate to simply link to its contained resources.
   */
  BasicContainer: new LitVocabTerm(_NS('BasicContainer'))
    .addLabel('', 'BasicContainer')
    .addComment('', `An LDPC that uses a predefined predicate to simply link to its contained resources.`)
,

  /**
   * A Linked Data Platform RDF Source (LDP-RS) that also conforms to additional patterns and conventions for managing membership. Readers should refer to the specification defining this ontology for the list of behaviors associated with it.
   */
  Container: new LitVocabTerm(_NS('Container'))
    .addLabel('', 'Container')
    .addComment('', `A Linked Data Platform RDF Source (LDP-RS) that also conforms to additional patterns and conventions for managing membership. Readers should refer to the specification defining this ontology for the list of behaviors associated with it.`)
,

  /**
   * A HTTP-addressable resource whose lifecycle is managed by a LDP server.
   */
  Resource: new LitVocabTerm(_NS('Resource'))
    .addLabel('', 'Resource')
    .addComment('', `A HTTP-addressable resource whose lifecycle is managed by a LDP server.`)
,

  /**
   * A Linked Data Platform Resource (LDPR) whose state is represented as RDF.
   */
  RDFSource: new LitVocabTerm(_NS('RDFSource'))
    .addLabel('', 'RDFSource')
    .addComment('', `A Linked Data Platform Resource (LDPR) whose state is represented as RDF.`)
,

  /**
   * Links a container with resources created through the container.
   */
  contains: new LitVocabTerm(_NS('contains'))
    .addLabel('', 'contains')
    .addComment('', `Links a container with resources created through the container.`)
,

  //
  // Marker allowing us put commas at the end of all lines above (only the last line does not have a comma).
  //
  END_OF_VOCAB: 'End of vocab.'
}
